language: node_js
node_js: stable

install: npm install

stages:
  - name: storybook
    if: branch = develop  # Push to devlop or PR to develop

jobs:
  include:
    - stage: tests
      script: npm run test

    - stage: build
      script: npm run build:production
      before_deploy: tar -zcvf $TRAVIS_BUILD_DIR/lime-app-$TRAVIS_BRANCH.tar.gz build
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: $TRAVIS_BUILD_DIR/lime-app-$TRAVIS_BRANCH.tar.gz"
        skip_clean: true
        on:
          tags: true

    - stage: storybook
      script:
        # Build storybook
        - npm run storybook:build
